#!/usr/bin/env node
const { Console } = require('@formidablejs/framework');

/**
 * --------------------------------------------------------------------------
 * Run The Craftsman Application
 * --------------------------------------------------------------------------
 *
 * When running the console application, Formidable will attempt to load the
 * console.imba script from the bootstrap directory. This script will be ran
 * using the "ImbaR" runtime. Both the runtime and console script can be
 * changed by providing the paths to the runtime and console scripts in the
 * "make" function.
 *
 * You may notice that running the console application is very slow. This is
 * because the console application is being compiled on the fly. To speed up
 * things, you can run the "build" script to pre-compile or "console:watch"
 * to continuously compile the console application. You can then set "prod"
 * to "true" in the "run" function.
 *
 * @example
 * 		// Running compiled console application
 * 		Console.make().run({ prod: true });
 */

Console.make().run({ prod: false });
